name: eloquence_flutter
description: Application de coaching vocal basée sur Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# Version + info de build
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dépendances du projet
dependencies:
  flutter:
    sdk: flutter

  # Interface utilisateur
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Gestion d'état
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  
  # Injection de dépendances
  get_it: ^7.6.4
  
  # Audio
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Services en ligne
  supabase_flutter: ^1.10.25
  http: ^1.1.0
  dio: ^5.3.3
  
  # Navigation
  go_router: ^12.1.1
  
  # Stockage local
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2
  equatable: ^2.0.5
  uuid: ^4.1.0
  
  # Configuration
  yaml: ^3.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2

# Configurations du launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#6421f3"
    theme_color: "#6421f3"

# Configuration Flutter
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/config/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
