services:
  livekit:
    image: livekit/livekit-server:v1.5.2
    ports:
      - "7880:7880"
      - "7881:7881" 
      - "3478:3478/udp"
      - "50000-50019:50000-50019/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge
